### ISSUE TITLE
Enchantment glint isn't rendered correctly

### ISSUE THREAD

**Issue by supsm** [spiralhalo/LumiLightsArchive#14]
When rendering enchanted items, they are rendered with black dots on them instead of the actual enchantment glint.
![image](https://user-images.githubusercontent.com/60897356/101293020-f7c78600-37c7-11eb-8e92-59696da2819d.png)
It can also be seen through blocks.
![image](https://user-images.githubusercontent.com/60897356/101293046-1168cd80-37c8-11eb-9034-1ff94cf8e012.png)

**Comment by spiralhalo** [comment]
Probably a Canvas bug. Can't confirm with Grondag yet as he's occupied with fixing the culling bug.
