### ISSUE TITLE
Entities appear too white

### ISSUE THREAD

**Issue by supsm** [spiralhalo/LumiLightsArchive#15]
Lumi lights makes some entities appear too white. I've seen this occur with spiders and magma cubes, but I don't think it happens in blazes and wither skeletons.
Without lumi lights:
![2020-12-08_12 50 16](https://user-images.githubusercontent.com/60897356/101540192-81a45a00-3954-11eb-9ba5-20391a93426d.png)

With lumi lights: 
![2020-12-08_12 49 36](https://user-images.githubusercontent.com/60897356/101540202-849f4a80-3954-11eb-93e4-274469b8eadf.png)

**Comment by spiralhalo** [comment]
That screenshot is from Lumi Lights PBR so I'm assuming it _might_ not apply to the hdr branch. Try [version 0.2](https://github.com/spiralhalo/LumiLightsPBR/releases/tag/v0.2) of Lumi PBR and see if the issue persists.

**Comment by supsm** [comment]
I think the issue has been fixed. Thanks!
